exe_perspective = {
    "Cyberpunk2077.exe": "fps",
    "GTA5_Enhanced.exe": "3ps",
    "DyingLightGame_x64_rwdi.exe": "fps",
    "FarCry4.exe": "fps",
    "Borderlands4.exe": "fps",
    "portal2.exe": "fps",
    "FarCry5.exe": "fps",
    "hl2.exe": "fps",
    "Overwatch.exe": "fps",
    "Subnautica.exe": "fps",
    "RDR2.exe": "3ps",
    "DyingLightGame_TheBeast_x64_rwdi.exe": "fps",
    "GTA5.exe": "3ps",
    "Remnant2-Win64-Shipping.exe": "3ps",
    "FortniteClient-Win64-Shipping.exe": "3ps",
    "MCC-Win64-Shipping.exe": "fps",
    "MirrorsEdgeCatalyst.exe": "fps",
    "JustCause3.exe": "3ps",
    "re8.exe": "fps",
    "MirrorsEdge.exe": "fps",
    "hl.exe": "fps",
    "re7.exe": "fps",
    "AmnesiaTheBunker.exe": "fps",
    "DyingLightGame.exe": "fps",
    "deadlock.exe": "fps",
    "tlou-ii.exe": "3ps",
    "SkyrimSE.exe": "fps",
    "iw3sp.exe": "fps",
    "cod.exe": "fps",
    "Ghostrunner-Win64-Shipping.exe": "fps",
    "farcry3_d3d11.exe": "fps",
    "NMS.exe": "fps",
    "FalloutNV.exe": "fps",
    "FragPunk.exe": "fps",
    "OLGame.exe": "fps",
    "Warhammer 40000 Space Marine 2 - Retail.exe": "3ps",
    "DOOMTheDarkAges.exe": "fps",
    "HITMAN3.exe": "3ps",
    "VALORANT-Win64-Shipping.exe": "fps",
    "BorderlandsGOTY.exe": "fps",
    "ThankYouVeryCool-Win64-Shipping.exe": "fps",
    "metro.exe": "fps",
    "farcry3.exe": "fps",
    "witness64_d3d11.exe": "fps",
    "HouseFlipper.exe": "fps",
    "MetroExodus.exe": "fps",
    "TOTClient-Win64-Shipping.exe": "fps",
    "Titanfall2.exe": "fps",
    "OblivionRemastered-Win64-Shipping.exe": "fps",
    "FarCryNewDawn.exe": "fps",
    "Fallout4.exe": "fps",
    "bf4.exe": "fps",
    "FarCry6.exe": "fps",
    "SkyrimTogether.exe": "fps",
    "DXHRDC.exe": "fps",
    "Visage-Win64-Shipping.exe": "fps",
    "eurotrucks2.exe": "fps",
    "DayZ_x64.exe": "3ps",
    "BlackOps3.exe": "fps",
    "Talos2-Win64-Shipping.exe": "fps",
    "r5apex_dx12.exe": "fps",
    "Gunfire Reborn.exe": "fps",
    "Prey.exe": "fps",
    "The Stanley Parable Ultra Deluxe.exe": "fps",
    "sekiro.exe": "3ps",
    "MCCWinStore-Win64-Shipping.exe": "fps",
    "DOOMEternalx64vk.exe": "fps",
    "F1_24.exe": "fps",
    "Necropolis.exe": "3ps",
    "PowerWashSimulator.exe": "fps",
    "BioShockInfinite.exe": "fps",
    "Talos.exe": "fps",
    "PathOfExileSteam.exe": "3ps",
    "Crysis-c1-launcher.exe": "fps",
    "Touhou Mystia Izakaya.exe": "3ps",
    "bf1.exe": "fps",
    "iw5sp.exe": "fps", # mw3
    "Shadows of Doubt.exe": "fps",
    "BlackOpsColdWar.exe": "fps",
    "Frog_Detective_3.exe": "fps",
    "Warframe.x64.exe": "3ps",
    "SplitFiction.exe": "3ps",
    "anuket_x64.exe": "fps", # BLOOD - retro doomlike
    "REPO.exe": "fps",
    "Discovery.exe": "fps",
    "AI.exe": "fps", # alien isolation
}

"""
Excluded: 

Discord.exe (non-game)
explorer.exe (non-game)
MuMuNxDevice.exe (Android emulator component)
RobloxPlayerBeta.exe (platform; perspective varies by experience)
"""